# -*- coding: utf-8 -*-
"""COREVQA Demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpuTta5tSzktiCo9xN4CtE9P1pmYV0ax
"""

!pip install pillow pandas tqdm huggingface_hub

import matplotlib.pyplot as plt
from PIL import Image
import pandas as pd
import os
import zipfile
from huggingface_hub import hf_hub_download

CSV_PATH = hf_hub_download(repo_id="COREVQA2025/COREVQA", filename="COREVQA.csv", repo_type="dataset")

UNZIP_DIR_TRAIN01 = "/content/crowdhuman_train01"
UNZIP_DIR_TRAIN02 = "/content/crowdhuman_train02"
IMAGE_FOLDER_TRAIN01 = os.path.join(UNZIP_DIR_TRAIN01, "Images")
IMAGE_FOLDER_TRAIN02 = os.path.join(UNZIP_DIR_TRAIN02, "Images")

try:
    zip_path_01 = hf_hub_download(repo_id="COREVQA2025/COREVQA", filename="CrowdHuman_train01.zip", repo_type="dataset")
    os.makedirs(UNZIP_DIR_TRAIN01, exist_ok=True)
    with zipfile.ZipFile(zip_path_01, 'r') as zip_ref:
        zip_ref.extractall(UNZIP_DIR_TRAIN01)
except:
    pass

try:
    zip_path_02 = hf_hub_download(repo_id="COREVQA2025/COREVQA", filename="CrowdHuman_train02.zip", repo_type="dataset")
    os.makedirs(UNZIP_DIR_TRAIN02, exist_ok=True)
    with zipfile.ZipFile(zip_path_02, 'r') as zip_ref:
        zip_ref.extractall(UNZIP_DIR_TRAIN02)
except:
    pass

import pandas as pd
df = pd.read_csv(CSV_PATH, encoding="utf-8-sig")
image_id_col = "image_id"
question_col = "question"
answer_col = "answer"

assert all(col in df.columns for col in [image_id_col, question_col, answer_col])

def display_question_and_image(index, dataframe):
    if not (0 <= index < len(dataframe)):
        return

    row = dataframe.iloc[index]
    image_id_csv = str(row[image_id_col])
    question = str(row[question_col])
    answer = str(row[answer_col])

    image_path = None
    if '/' in image_id_csv:
        folder_prefix, filename = image_id_csv.split('/', 1)
        if folder_prefix == "train01":
            image_path = os.path.join(IMAGE_FOLDER_TRAIN01, filename)
        elif folder_prefix == "train02":
            image_path = os.path.join(IMAGE_FOLDER_TRAIN02, filename)
    else:
        path1 = os.path.join(IMAGE_FOLDER_TRAIN01, image_id_csv)
        path2 = os.path.join(IMAGE_FOLDER_TRAIN02, image_id_csv)
        if os.path.exists(path1):
            image_path = path1
        elif os.path.exists(path2):
            image_path = path2

    if image_path and os.path.exists(image_path):
        img = Image.open(image_path)
        plt.figure(figsize=(12, 8))
        plt.imshow(img)
        plt.title(f"{answer}: {question}", fontsize=14)
        plt.axis('off')
        plt.show()

for i in range(1, 3):
  display_question_and_image(i, df)